Adds JSDoc
JoeBanks13/webhook-discord pull request #11
Opened 2018-04-25 15:45 UTC by Haxified1

I'm bored on my train and on my phone so I don't know what to do. Please  #don't decline because you don't like me Josef.

2018-04-25 16:09 UTC, jb3 requested changes
Comments left

2018-04-25 17:08 UTC, Haxified1 commented on lib/webhook.js
> +            "username": names,
oops

2018-04-25 17:08 UTC, Haxified1 commented on lib/webhook.js
> +            "username": names,
typo

2018-04-25 17:10 UTC, Haxified1 commented
Look good? My phone typing is not great :/

2018-04-25 19:05 UTC, jb3 requested changes
Just need the following addressing, rest of it looks good

2018-04-25 19:05 UTC, JoeBanks13 commented on lib/webhook.js
> +        let payload= {
Space here should not have been removed

2018-04-26 11:48 UTC, Haxified1 commented
Done

2018-04-26 16:00 UTC, Haxified1 commented
Fixed another smol thing.

2018-04-26 17:42 UTC, jb3 approved these changes

2018-04-26 17:42 UTC, JoeBanks13 commented
Looks good to me, cheers for that one :+1:

2018-04-26 17:42 UTC, merged

2024-09-18 08:20 UTC, Mstone87 commented on lib/webhook.js
> +        let payload= {
Sugabitcoin